### ISSUE TITLE
Still shows the timer

### ISSUE THREAD

**Issue by Hamybal** [FXbiker/Voicemeeter-Potato-Activator#1]
Hey thanks for the repo, I have first tried your bat with administrator and afterwards i've set code manually but after restarting my pc it still immediately shows the timer. Looking at the time of your post and the latest update of voicemeeter we should both be using the same version.

Furthermore have a good one!

**Comment by FXbiker** [comment]
Yes, I have found that manually incrementing the code up by 1 HEX place until the timer doesn't show up anymore is the best way to do it as of now: do this until the timer comes back and use the last HEX code that removed the timer, it should remove the timer for a few days before you will have to do this again...

**Comment by MrJaco** [comment]
> Yes, I have found that manually incrementing the code up by 1 HEX place until the timer doesn't show up anymore is the best way to do it as of now: do this until the timer comes back and use the last HEX code that removed the timer, it should remove the timer for a few days before you will have to do this again...
> 
> Edit: Am working on an improved script to do this automatically and conducting experiments to improve the script but this will take time...

Can you tell me how to "increment the code up by 1 HEX manually"? I tried to add by 1 decimal, 16 decimals, 10 decimals, but its not working. Ex. 738879 is B463F, which is the seccond in hex or decimal?

**Comment by FXbiker** [comment]
I have concluded my research and it seems that every 32 days the HEX code changes by 2 in the 2nd column (simply the hex code increments by a decimal value of 32 every 32 days) am currently writing a script to do do this. And code is a regedit variable under path "Computer\HKEY_CURRENT_USER\VB-Audio\VoiceMeeter" you must right click and click "modify" to change the variable in regedit.

**Comment by RenanSui** [comment]
Sorry, can you be a little more specific in your README file?

Do we need to increment the decimals by 1, 16 or 32?

Is the file to be executed the Script V2.py?

Does VoiceMeeter need to be open or closed?

**Comment by FXbiker** [comment]
sorry for the late reply, voicemeeter needs to be restarted every time you change the decimal value, this is why i recommend using task manager to force close voicemeeter.

also increase the decimal value by as much as you would like until the timer disappears, i recommend incrementing by 16 then refining to the lowest possible value that launches voicemeter without a timer.

and yes, the script2.py file is what you are looking for, i have it running from startup through a bat file that simply runs the file and opens voicemeeter

might make a video tutorial for these steps but it will be alot of effort

**Comment by IamHisekin** [comment]
I'm not sure if this helps, but I usually work around its trial period by using a program that freezes Voicemeeter's timedata to the same installation date. I've been using it like this for about 4 months without any major issues.

Do you think you could build something based on this? Freezing Voicemeeter's date seems promising.

**Comment by FXbiker** [comment]
please could you link me this program?

**Comment by IamHisekin** [comment]
I apologize for the delay in responding @FXbiker .

The program I'm using to bypass the Voicemeeter trial is the one in the link below.
https://www.nirsoft.net/utils/run_as_date.html
